import { Elysia } from 'elysia';
const g = globalThis as Record<string, unknown>;
const logs: unknown[] = []; const origLog = console.log; const origErr = console.error;
console.log = (x: unknown) => logs.push(x); console.error = () => {};
g['cors'] = () => new Elysia(); g['corsOrigin'] = 'http://localhost:4200'; g['realDb'] = { query: 'q' };
g['isValidAdminAuth'] = async () => false;
g['loadProduct'] = async (id: string) => { if (id === '11111111-1111-4111-8111-111111111111') throw new Error('duplicate key DETAIL: Key (phone)=(+79991234567)'); return undefined; };
g['saveProduct'] = async () => { throw new Error('never'); };
const { app } = await import('./elysia-playbook.ts');
const show = async (label: string, req: Request) => { const r = await app.handle(req); origLog(label.padEnd(26), r.status, (await r.text()).slice(0, 160), r.headers.get('www-authenticate') ?? ''); };
await show('unknown error', new Request('http://localhost/products/11111111-1111-4111-8111-111111111111'));
await show('domain 404', new Request('http://localhost/products/22222222-2222-4222-8222-222222222222'));
await show('bad param (422)', new Request('http://localhost/products/not-a-uuid'));
await show('bad body (422)', new Request('http://localhost/products', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ slug: '', name: 'Mug', priceMinor: -1, currency: 'RUB', stockCount: 1 }) }));
await show('malformed JSON', new Request('http://localhost/products', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{nope' }));
await show('no such route', new Request('http://localhost/nope'));
await show('admin, no creds', new Request('http://localhost/admin/orders'));
await new Promise((r) => setTimeout(r, 30));
origLog('request-log lines fired:', logs.filter((l) => (l as { event?: string }).event === 'http_request').length, 'of 7');
